name:                poly-field-lens
version:             0.1.0.0
github:              "githubuser/poly-field-lens"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/poly-field-lens#readme>

dependencies:
- base >= 4.7 && < 5
- bifunctors
- lens
- total
- generic-lens
- generic-lens-core
- profunctors
- tagged
- vector

ghc-options:
- -Wall

library:
  source-dirs: src
